# Generated by Django 5.2 on 2025-05-08 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdtic', '0002_documentopdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentopdf',
            name='arquivo',
        ),
        migrations.RemoveField(
            model_name='documentopdf',
            name='titulo',
        ),
        migrations.AddField(
            model_name='documentopdf',
            name='pdf_arquivo',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
        migrations.AddField(
            model_name='documentopdf',
            name='pdtic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='pdtic.pdtic'),
        ),
    ]
